# general settings

# compare to base 
name: MONet-compare-t2
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 42

amp: false
compile: false

datasets:
  train:
    name: TrainSet
    type: SarDataset
    dataroot_gt: datasets/SARdata
    meta_info: datasets/train.txt

    io_backend:
      type: disk

    # data loader
    crop_pad_size: 64

    use_shuffle: true
    use_hflip: true
    use_rot: true

    num_worker_per_gpu: 4
    batch_size_per_gpu: 8

    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: ValSetAll
    type: SarDataset
    dataroot_gt: datasets/SARdata
    meta_info: datasets/val.txt

    io_backend:
      type: disk

    crop_pad_size: 512

    use_shuffle: true
    use_hflip: false
    use_rot: false

network_g:
  type: MONet

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  check_resume: true

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: !!float 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepRestartLR
    milestones: [40000]

  total_iter: 55000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean
  
  pixel_opt_1:
    type: GradMSELoss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  use_image: true  # for eval

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
# dist_params:
#   backend: nccl
#   port: 29500
